services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: db
    env_file: db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file: frontend.env
    ports:
      - 3000:3000
    depends_on:
      - backend
